//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billiard_Loft_Membership_List
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public Int64 Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string fullName { get; set; }
        public string membershipStartDate { get; set; }
        public string membershipEndDate { get; set; }
        public bool membershipExpired { get; set; } 
    }
}
